### ISSUE TITLE
Some maps can terminate early and not have new tiles to spawn

### ISSUE THREAD

**Issue by acr-gaming** [Daloupe/rogue-tower-research#1]
https://github.com/Daloupe/rogue-tower-research/blob/main/Patches.cs#L38

It's possible the above doesn't get called per level because some maps get closed off such as:
![image](https://user-images.githubusercontent.com/101527326/159300379-94de78a8-57f4-4b26-8953-c8859d42cc39.png)

someone mentioned in discord not sure if your in there thought i'd drop in here

thanks!

**Comment by JackyDoesCoding** [comment]
yeah i had this issue, i'm the person acr is referring to. im definitely in agreement with their assessment of the situation

**Comment by Daloupe** [comment]
Oh didn't know there was a discord! Interesting I didn't think about this case, i'll look for a better trigger.

**Comment by acr-gaming** [comment]
https://discord.com/invite/2brzHhh6k9

Check it out! There is a channel for mods.

**Comment by Daloupe** [comment]
Fixed in 0.0.3
