### ISSUE TITLE
Forced Research

### ISSUE THREAD

**Issue by JackyDoesCoding** [Daloupe/rogue-tower-research#2]
If you click the "research" button, there's no way to change your mind and close out of it. Makes it very frustrating when the last card left is a mana bolt, and you don't have mana capabilities... I suppose you could still click the upgrade card and then go back into the tower and click cancel research, but i think there's also a bug with this that triggers the next level to be ready, so i can click another tile and have an additional wave start, when there enemies from the previous level are still going.
![image](https://user-images.githubusercontent.com/33379998/159335258-9efe1efe-a588-49e9-acd7-3ead15b2b330.png)

**Comment by JackyDoesCoding** [comment]
![image](https://user-images.githubusercontent.com/33379998/159338535-b59a94b0-e1f6-4c96-8f4c-66f20da7521c.png)
this is what i mean by that last bit... i close out of the research selection in the middle of the level, and it pops this up. enemies still swarming... but i can expand still

**Comment by Daloupe** [comment]
Oh yeah cos i had it unhide the expand buttons regardless of whether a wave was still in progress. I'll make it only unhide the expand buttons if they weren't hidden to begin with.

Regarding the having to select and then cancel, yeah it's a pain and maybe not obvious. This is cos i tried to keep things simple and reuse as much of the existing stuff to begin with. There is probably a way to add a new cancel button, but might hold off until i find the time to create a separate card ui that's less hacky.

**Comment by Daloupe** [comment]
Bug fixed in 0.0.3, i'll raise a separate issue for the enhancement suggestion.
